version: '{build}'
image: 
 - Visual Studio 2017
configuration: Release
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
branches:
  only:
  - master
clone_depth: 1
nuget:
  disable_publish_on_pr: true
test_script:
- ps: .\run-sonar.ps1
build_script:
- ps: .\build.ps1
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.xml
  name: xUnit Test Results
deploy:
- provider: NuGet
  name: nuget_release
  api_key:
    secure: bzqgy/P+CNVgbHxLTjmag6GlgeKG4n0Dgj10dM0jjegj0LtNHpepVXBJ/nEUmL1M
  on:
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - nazmialtun@windowslive.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false