version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  sonar_token:
    secure: bb48ce419887374c832debe93ea0ee5b9d29914d
branches:
  only:
  - master
image: 
 - Visual Studio 2017
configuration: Release
clone_depth: 1
nuget:
  disable_publish_on_pr: true
test_script:
- ps: .\run-sonar.ps1
build_script:
- ps: .\Build.ps1
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.xml
  name: xUnit Test Results
deploy:
- provider: NuGet
  name: nuget_release
  api_key:
    secure: fEPibi05QGFadnQVP5zulZ51Xp5qXo1vj4FEGvWlVB2ds/IebcmjGzDIWIj4IYOf
  on:
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - nazmialtun@windowslive.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false